### Hit CTRL+SHIFT+F5 to reload config

font-family                         MesloLGLNFM-Regular
font_size                           21

background_opacity                  0.8
background_blur                     64
dynamic_background_opacity          yes

confirm_os_window_close             0

macos_option_as_alt                 yes
macos_quit_when_last_window_closed  yes
